###
GET http://localhost:8080/api/v1/challenges/55c212e6-7a60-4cfe-95a1-3924b40424ac
Content-Type: application/json


###

POST http://localhost:8080/api/v1/challenges
Content-Type: application/json

{
  "name": "Pushkin444",
  "goal": 300,
  "ownerUserId": "3",
  "chatId": "54321",
  "userIds": [
    "1",
    "2",
    "3"
  ]
}
###
GET http://localhost:8080/api/v1/challenges/chat/54321

###
POST http://localhost:8080/api/v1/submissions
Content-Type: application/json

{
  "userId": "1",
  "challengeId": "55c212e6-7a60-4cfe-95a1-3924b40424ac",
  "value": 100
}

###
POST http://localhost:8080/api/v1/challenges/activate
Content-Type: application/json

{
  "challengeId": "55c212e6-7a60-4cfe-95a1-3924b40424ac"
}
