app.http.bot: challengrbot
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/challenger?currentSchema=challenger_core
    username: challenger_owner
    password: --OVERRIDE--
    hikari:
      maximum-pool-size: 50
      auto-commit: true
      minimum-idle: 5
telegram-bot:
  ui:
    url: https://challengr.site:8443/ui
  name: challenger
  token: --OVERRIDE--
  api-url: https://api.telegram.org/
  webhook-path: https://692b-188-243-227-243.ngrok.io
spring-boot.build-image.imageName: agackovka/core
#logging:
#  level:
#    root: trace
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
server:
  ssl:
    key-store: classpath:challenger.p12
    key-store-type: pkcs12
    key-alias: challenger
    protocol: TLS
    enabled-protocols: TLSv1.2
  port: 8443